from src.exceptions.common.ConflictError import ConflictError


class PersonAlreadyExistsError(ConflictError):
    pass
