from src.exceptions.common.ConflictError import ConflictError


class UserAlreadyExistsError(ConflictError):
    pass
